### ISSUE TITLE
`[BUG]` Blueballed Counter is missplaced

### ISSUE THREAD

**Issue by Cheese-Curd** [Sanscode1937/OG-ENGINE#1]
![image](https://user-images.githubusercontent.com/51841108/149858462-ea352162-0528-4008-ab77-b34469c74f05.png)
Blueballed counter is supposed to go under the difficulty

**Comment by Sanscode1937** [comment]
I like to place text on that place but fine

**Comment by Sanscode1937** [comment]
and did you see comment?
