### ISSUE TITLE
`[WARNING] Cannot add a ``null`` object to a FlxGroup.` in console when playing Milf

### ISSUE THREAD

**Issue by Cheese-Curd** [Sanscode1937/OG-ENGINE#2]
![image](https://user-images.githubusercontent.com/51841108/149858604-591332c6-a006-4475-8e05-38111d961fc2.png)
Happens on song load

**Comment by Sanscode1937** [comment]
ignore that

**Comment by Cheese-Curd** [comment]
bruh
